elementary/wingpanel-indicator-bluetooth

- src/Widgets/Views/MainView.vala
> Move separator out of the device list

- src/Widgets/Views/MainView.vala
There's a Gtk Widget for this, no need for a custom widget
> Use Gtk.ModelButton

- meson.build
- meson/post_install.py
We made an oops and forgot to do this
> Install settings schema

- src/Widgets/PopoverWidget.vala
This feature is now provided by Gtk
> PopoverWidget: use native Gtk.ScrolledWindow

- src/Widgets/Device.vala
* GObject-style construction
* Adjust whitespace
* Reduce variable scope where possible
> Device.vala: GObject-style

- .travis.yml
- src/Widgets/PopoverWidget.vala
This also changes travis to build against `juno-unstable`
> Update to latest wingpanel API

- src/Indicator.vala
- src/Widgets/PopoverWidget.vala
The popover closes already without this
> Get rid of unnecessary close request signal

- src/Services/Manager.vala
Remove unused methods and signals. Reduce scope of `remove_path`
> Manager.vala: Remove unused methods

- src/Services/Manager.vala
- src/Widgets/Device.vala
- src/Widgets/DisplayWidget.vala
- src/Widgets/PopoverWidget.vala
Fixes #1 
Ensure indicator and popover reflect reality; avoid race.
Also fixes some discrepancies found between switchboard plug and wingpanel plug while investigating this issue.
> Fix freeze if power off when connected.

- src/Widgets/Device.vala
Fixes: #69
Result (with test device names):
> Escape device name

- src/Widgets/PopoverWidget.vala
Fixes #74 
Replaces the Gtk.Box with a Gtk.ListBox and adds the same sort function we use in the Bluetooth plug
> PopoverWidget: Use a listbox for devices and sort

- src/Widgets/Device.vala
> Device: add status images

- data/bluetooth.appdata.xml.in
- meson.build
> Release 2.1.4

- src/Widgets/PopoverWidget.vala
> Prevent device duplicates

- data/indicator.css
As reported in https://github.com/elementary/wingpanel-indicator-notifications/issues/63
> Indicator.css: Fix flashing animation

- src/Widgets/Device.vala
> Device: add a fallback device name for Headphones

- ebt/Application.vala
- ebt/Dialog/BtReceiver.vala
- ebt/Dialog/BtSender.vala
Also use GLib.KeyFile to create the contract entry.
> Use GLib.Markup.printf_escaped when possible

- ebt/Application.vala
* Get rid of single-use methods
* Only create contract if it doesn't already exist
* Don't force a newline after errors and remove extraneous "error" text
> Application: simplify contract creation

- data/bluetooth.metainfo.xml.in
- data/gresource.xml
- src/Widgets/DisplayWidget.vala
> Manually add resourced icons to path

- data/bluetooth.metainfo.xml.in
- meson.build
> Release 7.0.1

- ebt/Dialog/DeviceRow.vala
- src/Widgets/Device.vala
> Use emblem- icons instead of user-

- .github/workflows/main.yml
- README.md
- meson.build
Seems to be leftover from when bluetooth-daemon was part of this repo
> Remove unused LibNotify dep

- debian/control
Goes with https://github.com/elementary/wingpanel-indicator-bluetooth/pull/220
> Control: remove notify dep

- src/Widgets/Device.vala
* Bump copyright header
* Code style
* Set pixel size on image since we won't have `IconSize.DIALOG` in GTK4
* child property of Revealer, Overlay, and ListBoxRow
> Device: GTK4 Prep

- src/Widgets/PopoverWidget.vala
* Bump copyright header
* Code style
* Use child property for ScrolledWindow, Revealer
* Can't `get_children` in GTK4 so use `get_row_at_index`
> PopoverWidget: GTK4 prep

- src/Widgets/DisplayWidget.vala
Can't subclass Gtk.Spinner in GTK4
> DisplayWidget: subclass Gtk.Bin
